server:
  port: 8090

spring:
  datasource:
    url: ENC(t01noauVqWuCiiHxX7tv4syADosZQhwzFPvZSf34QyG9nuvYMnvVsX27egmcIJR3MQgIiEtyAzTgT1xclv8+Rnxdj82HHhvhXYXn52h6NplHdjj7jvsPi13D5ztsmEoDZIKa1NwzCGBQveAnf8aPHSPZ/csqlJDa)
    username: ENC(WiLx4Xtm64u0B/aQoITtTg==)
    password: ENC(gBadhgJSV4yFjijC4PFYjlhj8RBHFBiU)
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
      pool-name: metamarket-db-pool
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    generate-ddl: true

management:
  endpoints:
    web:
      base-path: /monitor


jasypt:
  encryptor:
    bean: stringEncryptor
    password: ${JASYPT_PASSWORD}

